#!/usr/bin/env python3
"""Survey the Baltijets doc 003 BASIC command against public ROM/media pairings."""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "basic-factory-command-probe.md"
LAUNCH_PROBE = ROOT / "sync" / "basic_launch_probe.py"


@dataclass(frozen=True)
class FactoryCase:
    name: str
    rom: Path
    frame_cycles: int


@dataclass(frozen=True)
class EvidenceRow:
    monitor: str
    rom: str
    cartridge: str
    frame_cycles: str
    infra: str
    cart_overlay_reads: int
    pc_cart_count: int
    pc_cart_mode1: int
    pc_cart_mode2: int
    ram_writes: int
    ram_nonzero_bytes: int
    visible_pixels: int
    stop_pc: str
    mode: str


CASES = (
    FactoryCase("jmon22", ROOT / "roms" / "jmon22.bin", 200000),
    FactoryCase("jmon33", ROOT / "roms" / "jmon33.bin", 200000),
    FactoryCase("ekta37", ROOT / "roms" / "ekta37.bin", 40000),
)


def cell_text(cell: str) -> str:
    return cell.strip().strip("`")


def cell_int(cell: str) -> int:
    text = cell_text(cell)
    return int(text, 0) if text and text != "missing" else 0


def parse_evidence(report: Path) -> list[EvidenceRow]:
    rows: list[EvidenceRow] = []
    for line in report.read_text().splitlines():
        if not line.startswith("| "):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) != 19 or cells[0] in {"Monitor", "---"}:
            continue
        rows.append(
            EvidenceRow(
                monitor=cells[0],
                rom=cell_text(cells[1]),
                cartridge=cell_text(cells[2]),
                frame_cycles=cell_text(cells[3]),
                infra=cells[4],
                cart_overlay_reads=cell_int(cells[5]),
                pc_cart_count=cell_int(cells[6]),
                pc_cart_mode1=cell_int(cells[7]),
                pc_cart_mode2=cell_int(cells[8]),
                ram_writes=cell_int(cells[10]),
                ram_nonzero_bytes=cell_int(cells[13]),
                visible_pixels=cell_int(cells[15]),
                stop_pc=cell_text(cells[16]),
                mode=cell_text(cells[17]),
            )
        )
    return rows


def launch_status(report: Path) -> str:
    match = re.search(r"^Status: \*\*(.+?)\*\*$", report.read_text(), re.M)
    return match.group(1) if match else "UNKNOWN"


def run_case(case: FactoryCase, tmpdir: Path) -> tuple[FactoryCase, int, bool, str, list[EvidenceRow]]:
    report = tmpdir / f"{case.name}-A.md"
    env = os.environ.copy()
    env.update(
        {
            "BASIC_LAUNCH_KEYS": "A",
            "BASIC_LAUNCH_ROM": str(case.rom),
            "BASIC_LAUNCH_FRAME_CYCLES": str(case.frame_cycles),
            "BASIC_LAUNCH_REPORT": str(report),
        }
    )
    proc = subprocess.run(
        [sys.executable, str(LAUNCH_PROBE)],
        cwd=ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    report_exists = report.exists()
    rows = parse_evidence(report) if report_exists else []
    status = launch_status(report) if report_exists else "REPORT MISSING"
    return case, proc.returncode, report_exists, status, rows


def main() -> int:
    runs = []
    with tempfile.TemporaryDirectory(prefix="basic-factory-command.") as tmp:
        tmpdir = Path(tmp)
        for case in CASES:
            runs.append(run_case(case, tmpdir))

    rows = [row for _, _, _, _, case_rows in runs for row in case_rows]
    reports_written = all(report_exists for _, _, report_exists, _, _ in runs)
    any_basic_ram_execution = any(status == "BASIC RAM EXECUTION REACHED" for _, _, _, status, _ in runs)
    any_overlay = any(row.cart_overlay_reads > 0 for row in rows)
    any_live_cart_fetch = any(row.pc_cart_mode2 > 0 for row in rows)
    status = "FACTORY BASIC COMMAND BOUNDARY PINNED" if reports_written and rows else "FACTORY BASIC COMMAND PROBE FAILED"

    lines = [
        "# BASIC factory-command probe",
        "",
        f"Status: **{status}**",
        "",
        "Baltijets factory document 003 says the removable 32K memory-expander BASIC",
        "check launches with command `A` and expects a BASIC banner plus `READY`.",
        "This guard runs that `A` command against the public monitor ROMs and both",
        "public BASIC payload shapes already used by `sync/basic_launch_probe.py`.",
        "",
        "## Command",
        "",
        "```sh",
        "sync/basic_factory_command_probe.py",
        "```",
        "",
        "Each row is generated by `sync/basic_launch_probe.py` with",
        "`BASIC_LAUNCH_KEYS=A`; non-zero launch-probe exits are expected when a",
        "candidate does not reach BASIC RAM execution.",
        "",
        "## Evidence",
        "",
        "| Monitor | ROM | Cartridge | Frame cycles | Launch status | Launch exit | Infra | Cart overlay reads | PC in `0x4000..0xBFFF` | Mode-1 PC cycles | Mode-2 PC cycles | RAM writes | RAM nonzero bytes | Visible pixels | Stop PC | Mode |",
        "| --- | --- | --- | ---: | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |",
    ]
    for case, returncode, _, launch_state, case_rows in runs:
        if not case_rows:
            lines.append(
                f"| {case.name} | `{case.rom.relative_to(ROOT)}` | - | `{case.frame_cycles}` | "
                f"{launch_state} | `{returncode}` | FAIL | `0` | `0` | `0` | `0` | `0` | `0` | `0` | `0x0000` | `0` |"
            )
            continue
        for row in case_rows:
            lines.append(
                f"| {row.monitor} | `{row.rom}` | `{row.cartridge}` | `{row.frame_cycles}` | "
                f"{launch_state} | `{returncode}` | {row.infra} | "
                f"`{row.cart_overlay_reads}` | `{row.pc_cart_count}` | "
                f"`{row.pc_cart_mode1}` | `{row.pc_cart_mode2}` | "
                f"`{row.ram_writes}` | `{row.ram_nonzero_bytes}` | "
                f"`{row.visible_pixels}` | `{row.stop_pc}` | `{row.mode}` |"
            )

    lines.extend(
        [
            "",
            "## Disposition",
            "",
            f"- Probe reports generated: {'PASS' if reports_written else 'FAIL'}.",
            f"- At least one `A` candidate touched the cartridge overlay: {'YES' if any_overlay else 'NO'}.",
            f"- Any tested `A` candidate executed live cartridge-overlay opcodes in mode 2: {'YES' if any_live_cart_fetch else 'NO'}.",
            f"- Any tested `A` candidate reached the current BASIC RAM execution boundary: {'YES' if any_basic_ram_execution else 'NO'}.",
            "- Result: the factory `A` clue is now tracked as a reproducible boundary",
            "  for the public ROM/media pairings in this repo. Monitor 3.3 reaches the",
            "  same zero-filled RAM execution boundary as the earlier `B` run, but no",
            "  tested pairing executes live cartridge-overlay opcodes or reaches the",
            "  documented BASIC banner/`READY` acceptance oracle. That says the matching",
            "  monitor, removable-memory decode state, or BASIC media pairing is still",
            "  missing.",
        ]
    )
    lines.append("")

    REPORT.write_text("\n".join(lines))
    print(f"BASIC-FACTORY-COMMAND-PROBE: {'PASS' if status.endswith('PINNED') else 'FAIL'}")
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    return 0 if status.endswith("PINNED") else 1


if __name__ == "__main__":
    raise SystemExit(main())
