#!/usr/bin/env python3
"""Guard the recovered sheet-2 16 MHz crystal oscillator topology."""
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BOARD = ROOT / "kicad" / "juku.board.json"
REPORT = ROOT / "docs" / "master-oscillator-boundary.md"

REQUIRED = {
    "OSC_FB": {("D59", "9"), ("R31", "1"), ("R32", "1"), ("Z1", "1")},
    "OSC_PRE": {("D59", "8"), ("D59", "1"), ("R31", "2")},
    "XTAL_TRIM": {("Z1", "2"), ("C73", "1")},
    "OSC": {("D59", "2"), ("D59", "3"), ("D40", "2"), ("C73", "2")},
    "PST_CLK": {("D59", "4"), ("D44", "5"), ("R32", "2")},
}


def row(items: list[str]) -> str:
    return "| " + " | ".join(items) + " |"


def main() -> int:
    board = json.loads(BOARD.read_text(encoding="utf-8"))
    chips = {item["ref"]: item for item in board["chips"]}
    actual = {
        name: {tuple(node) for node in board["nets"].get(name, {}).get("nodes", [])}
        for name in REQUIRED
    }
    checks: list[tuple[str, bool, str]] = []
    for name, expected in REQUIRED.items():
        checks.append((
            f"`{name}` preserves every sheet-2 endpoint",
            expected <= actual[name],
            ", ".join(f"{ref}.{pin}" for ref, pin in sorted(actual[name])) or "-",
        ))
    checks.extend((
        (
            "R31/R32 are modeled as physical oscillator parts",
            chips.get("R31", {}).get("type") == "R_AXIAL" and chips.get("R32", {}).get("type") == "R_AXIAL",
            f"R31={chips.get('R31', {}).get('value', '-')}; R32={chips.get('R32', {}).get('value', '-')}",
        ),
        (
            "Crystal and trimmer have no omitted endpoint",
            all(any((ref, pin) in endpoints for endpoints in actual.values())
                for ref in ("Z1", "C73") for pin in ("1", "2")),
            "Z1.1/Z1.2 and C73.1/C73.2 are assigned",
        ),
        (
            "R31 target-board value conflict remains explicit",
            "820" in chips.get("R31", {}).get("prov", {}).get("pins", "")
            and chips.get("R31", {}).get("value") == "1к",
            "owner board #2: 1K0; sheet-2 scan: 820 ohm",
        ),
        (
            "D59 section 5->6 is traced into the mux-enable links",
            ["D59", "5"] not in board.get("no_connects", [])
            and ["D59", "6"] not in board.get("no_connects", [])
            and {("D59", "5"), ("E14", "1")} <= {
                tuple(node) for node in board["nets"]["VID_MUX_G"]["nodes"]
            }
            and {("D59", "6"), ("E13", "1")} <= {
                tuple(node) for node in board["nets"]["CPU_MUX_G"]["nodes"]
            },
            "full-resolution sheet 2: D59.5 feeds E14/video /G and D59.6 feeds E13/CPU /G",
        ),
    ))
    ok = all(result for _, result, _ in checks)
    status = "MASTER OSCILLATOR TOPOLOGY GUARDED" if ok else "MASTER OSCILLATOR CHECK FAILED"
    lines = [
        "# Master oscillator boundary",
        "",
        "Status date: 2026-07-22.",
        "",
        f"Status: **{status}**",
        "",
        "The sheet-2 16 MHz oscillator around D59 is now electrically complete in",
        "the source board model. The factory assembly drawing independently fixes",
        "R31 vertically between Z1 and D59 and R32 horizontally above D59; the owner",
        "photograph confirms both physical bodies. Board #2 visibly carries 1K0 at",
        "R31 while the schematic scan reads 820 ohm, so the replica target retains",
        "the photographed 1 kOhm population and records the source-revision conflict.",
        "",
        "The separate `XTAL16M` rail remains deliberately unmerged: its suspected",
        "continuation from `OSC` still needs the pending sheet-2 bundle-tag read.",
        "",
        "## Checks",
        "",
        "| Check | Result | Evidence |",
        "| --- | --- | --- |",
    ]
    lines.extend(row([name, "PASS" if result else "FAIL", evidence]) for name, result, evidence in checks)
    lines.extend(("", "Generated by `python3 scripts/report_master_oscillator_boundary.py`." , ""))
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(status)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
