#!/usr/bin/env python3
"""Emit the rev B mem-card LVS map (TD.6.1) from the board generator's pin tables.

Single source of truth for pin numbering is gen_revb_boards.py's CHIP_TYPES; this
emitter re-exports the relevant slices as sync/lvs.py's map format so the pinmap can
never drift from the board.json (D1.22). The independently-authored artifact that
LVS actually checks is the structural netlist hdl/revb/revb_mem_lvs.v (TD.6.2).

map.json shape (see spinoffs/minimal-vga/sync/map.json):
  instances: board refdes -> HDL instance name (only the ICs; connectors/passives
             stay unmapped, so sync/lvs.py ignores them)
  pinmaps.kicad: chip TYPE -> {pin number -> logical pin name}; the logical name is
             the CHIP_TYPES net at that pin, which is exactly what the structural
             netlist wires that port to.
"""
import json
from pathlib import Path
import gen_revb_boards as g   # same directory; defines CHIP_TYPES, CARD_CHIPS

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "sync" / "revb_mem_map.json"

# mem-card IC refdes -> HDL instance name (the design-intent mapping).
MEM_INSTANCES = {"U1": "U_ROM", "U2": "U_SRAM", "U3": "U_DEC"}


def main():
    # types actually populated on the mem card
    mem_types = {typ for ref, typ in g.CARD_CHIPS["mem"]}
    pinmaps = {typ: dict(g.CHIP_TYPES[typ]) for typ in sorted(mem_types)}
    doc = {
        "_about": "Generated by gen_revb_lvs_map.py from gen_revb_boards.py CHIP_TYPES. "
                  "Do not edit by hand; regenerate.",
        "instances": dict(MEM_INSTANCES),
        "pinmaps": {"kicad": pinmaps},
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUT} ({len(pinmaps)} chip types, {len(MEM_INSTANCES)} instances)")


if __name__ == "__main__":
    main()
