#!/usr/bin/env python3
"""Emit the rev B mem-card LVS map (TD.6.1) from the board generator's pin tables.

Single source of truth for pin numbering is gen_revb_boards.py's CHIP_TYPES; this
emitter re-exports the relevant slices as sync/lvs.py's map format so the pinmap can
never drift from the board.json (D1.22). The independently-authored artifact that
LVS actually checks is the structural netlist hdl/revb/revb_mem_lvs.v (TD.6.2).

map.json shape (see spinoffs/minimal-vga/sync/map.json):
  instances: board refdes -> HDL instance name (only the ICs; connectors/passives
             stay unmapped, so sync/lvs.py ignores them)
  pinmaps.kicad: chip TYPE -> {pin number -> logical pin name}; the logical name is
             the CHIP_TYPES net at that pin, which is exactly what the structural
             netlist wires that port to.
"""
import json, sys
from pathlib import Path
import gen_revb_boards as g   # same directory; defines CHIP_TYPES, CARD_CHIPS

HERE = Path(__file__).resolve().parent
SYNC = HERE.parents[1] / "sync"

# Per-card IC refdes -> HDL instance name (design-intent mapping). Video deliberately
# maps every populated digital package; its oscillator is part of the clock chain.
INSTANCES = {
    "mem": {"U1": "U_ROM", "U2": "U_SRAM", "U3": "U_DEC"},
    "io":  {"U1": "U_UART", "U2": "U_IOSEL"},   # 8251 + I/O-select GAL (populated)
    "video": {
        "U1": "U_OSC", "U2": "U_HC_LO", "U3": "U_HC_VC", "U4": "U_VC_HI",
        "U5": "U_HDEC", "U6": "U_VDEC", "U7": "U_CTRL",
        "U8": "U_MUX0", "U9": "U_MUX1", "U10": "U_MUX2", "U11": "U_MUX3",
        "U12": "U_SCAN0", "U13": "U_SCAN1", "U14": "U_SCAN2", "U15": "U_SCAN3",
        "U16": "U_ADD", "U17": "U_ROW0", "U18": "U_ROW1", "U19": "U_SHIFT",
        "U20": "U_DBUF", "U21": "U_FB", "U22": "U_BLANK", "U23": "U_RGB",
    },
}

# Physical pin roles for the repeated Video-card packages.  Unlike the distinct
# GAL/SRAM tables, one role map can serve every instance of a repeated type while
# the structural Verilog independently says which board net occupies that role.
VIDEO_LVS_PINMAPS = {
    "OSC_25M175": {"1":"OE", "7":"GND", "8":"CLKOUT", "14":"VCC"},
    "ST_HC393": {"1":"CLK1", "2":"CLR1", "3":"Q1A", "4":"Q1B", "5":"Q1C",
        "6":"Q1D", "7":"GND", "8":"Q2D", "9":"Q2C", "10":"Q2B",
        "11":"Q2A", "12":"CLR2", "13":"CLK2", "14":"VCC"},
    "ACT_157": {"1":"SEL", "2":"I1A", "3":"I1B", "4":"Y1", "5":"I2A",
        "6":"I2B", "7":"Y2", "8":"GND", "9":"Y3", "10":"I3B",
        "11":"I3A", "12":"Y4", "13":"I4B", "14":"I4A", "15":"ENABLE_N",
        "16":"VCC"},
    "ACT_161": {"1":"CLR_N", "2":"CLK", "3":"D0", "4":"D1", "5":"D2",
        "6":"D3", "7":"ENP", "8":"GND", "9":"LOAD_N", "10":"ENT",
        "11":"Q3", "12":"Q2", "13":"Q1", "14":"Q0", "15":"RCO", "16":"VCC"},
    "TTL_283": {"1":"S1", "2":"B1", "3":"A1", "4":"S0", "5":"A0",
        "6":"B0", "7":"CIN", "8":"GND", "9":"COUT", "10":"S3",
        "11":"B3", "12":"A3", "13":"S2", "14":"A2", "15":"B2", "16":"VCC"},
    "ACT_273": {"1":"CLR_N", "2":"Q0", "3":"D0", "4":"D1", "5":"Q1",
        "6":"Q2", "7":"D2", "8":"D3", "9":"Q3", "10":"GND", "11":"CLK",
        "12":"Q4", "13":"D4", "14":"D5", "15":"Q5", "16":"Q6", "17":"D6",
        "18":"D7", "19":"Q7", "20":"VCC"},
    "ALS_166": {"1":"SER", "2":"A", "3":"B", "4":"C", "5":"D", "6":"CLK_INH",
        "7":"CLK", "8":"GND", "9":"CLR_N", "10":"E", "11":"F", "12":"G",
        "13":"H", "14":"QH", "15":"SH_LD_N", "16":"VCC"},
    "HCT_245": {"1":"DIR", "2":"A0", "3":"A1", "4":"A2", "5":"A3", "6":"A4",
        "7":"A5", "8":"A6", "9":"A7", "10":"GND", "11":"B7", "12":"B6",
        "13":"B5", "14":"B4", "15":"B3", "16":"B2", "17":"B1", "18":"B0",
        "19":"OE_N", "20":"VCC"},
    "HCT_08": {"1":"A1", "2":"B1", "3":"Y1", "4":"A2", "5":"B2", "6":"Y2",
        "7":"GND", "8":"Y3", "9":"A3", "10":"B3", "11":"Y4", "12":"A4",
        "13":"B4", "14":"VCC"},
    "ACT_08": {"1":"A1", "2":"B1", "3":"Y1", "4":"A2", "5":"B2", "6":"Y2",
        "7":"GND", "8":"Y3", "9":"A3", "10":"B3", "11":"Y4", "12":"A4",
        "13":"B4", "14":"VCC"},
    "SRAM_FB": {"1":"NC1", "2":"A16", "3":"A14", "4":"A12", "5":"A7", "6":"A6",
        "7":"A5", "8":"A4", "9":"A3", "10":"A2", "11":"A1", "12":"A0",
        "13":"DQ0", "14":"DQ1", "15":"DQ2", "16":"GND16", "17":"DQ3", "18":"DQ4",
        "19":"DQ5", "20":"DQ6", "21":"DQ7", "22":"CE1_N", "23":"A10", "24":"OE_N",
        "25":"A11", "26":"A9", "27":"A8", "28":"A13", "29":"WE_N", "30":"CE2",
        "31":"A15", "32":"VCC"},
}


def emit(card):
    types = {typ for ref, typ in g.CARD_CHIPS[card] if ref in INSTANCES[card]}
    pinmaps = {typ: dict(g.CHIP_TYPES[typ]) for typ in sorted(types)}
    if card == "video":
        pinmaps.update(VIDEO_LVS_PINMAPS)
    doc = {
        "_about": "Generated by gen_revb_lvs_map.py from gen_revb_boards.py CHIP_TYPES. "
                  "Do not edit by hand; regenerate.",
        "instances": dict(INSTANCES[card]),
        "pinmaps": {"kicad": pinmaps},
        **({"complete_instances": sorted(INSTANCES[card]),
            "close_nonpower_nets_of_complete_instances": False} if card == "video" else {}),
    }
    out = SYNC / f"revb_{card}_map.json"
    out.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {out.name} ({len(pinmaps)} chip types, {len(INSTANCES[card])} instances)")


def main():
    cards = [sys.argv[1]] if len(sys.argv) > 1 else list(INSTANCES)
    for c in cards:
        emit(c)


if __name__ == "__main__":
    main()
