#!/usr/bin/env python3
"""Emit the rev B mem-card LVS map (TD.6.1) from the board generator's pin tables.

Single source of truth for pin numbering is gen_revb_boards.py's CHIP_TYPES; this
emitter re-exports the relevant slices as sync/lvs.py's map format so the pinmap can
never drift from the board.json (D1.22). The independently-authored artifact that
LVS actually checks is the structural netlist hdl/revb/revb_mem_lvs.v (TD.6.2).

map.json shape (see spinoffs/minimal-vga/sync/map.json):
  instances: board refdes -> HDL instance name (only the ICs; connectors/passives
             stay unmapped, so sync/lvs.py ignores them)
  pinmaps.kicad: chip TYPE -> {pin number -> logical pin name}; the logical name is
             the CHIP_TYPES net at that pin, which is exactly what the structural
             netlist wires that port to.
"""
import json, sys
from pathlib import Path
import gen_revb_boards as g   # same directory; defines CHIP_TYPES, CARD_CHIPS

HERE = Path(__file__).resolve().parent
SYNC = HERE.parents[1] / "sync"

# Per-card IC refdes -> HDL instance name (design-intent mapping). Only the logic
# ICs that get LVS'd; connectors/passives/oscillators are unmapped (D1.22).
INSTANCES = {
    "mem": {"U1": "U_ROM", "U2": "U_SRAM", "U3": "U_DEC"},
    "io":  {"U1": "U_UART", "U2": "U_IOSEL"},   # 8251 + I/O-select GAL (populated)
    "video": {"U5": "U_HDEC", "U6": "U_VDEC", "U7": "U_CTRL", "U21": "U_FB"},
}


def emit(card):
    types = {typ for ref, typ in g.CARD_CHIPS[card] if ref in INSTANCES[card]}
    pinmaps = {typ: dict(g.CHIP_TYPES[typ]) for typ in sorted(types)}
    doc = {
        "_about": "Generated by gen_revb_lvs_map.py from gen_revb_boards.py CHIP_TYPES. "
                  "Do not edit by hand; regenerate.",
        "instances": dict(INSTANCES[card]),
        "pinmaps": {"kicad": pinmaps},
    }
    out = SYNC / f"revb_{card}_map.json"
    out.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {out.name} ({len(pinmaps)} chip types, {len(INSTANCES[card])} instances)")


def main():
    cards = [sys.argv[1]] if len(sys.argv) > 1 else list(INSTANCES)
    for c in cards:
        emit(c)


if __name__ == "__main__":
    main()
