#!/usr/bin/env python3
"""TG.3 / D1.15 mechanical mating + keying analysis. Run under freecadcmd:

    freecadcmd mate_check.py

Loads the four rev B card STEP models, measures each card's real component envelope
(the bounding-box extent normal to the board), and checks that cards seated in the
backplane at the contract slot pitch do not collide. Then analyses the reversed-card
keying question (D1.4/D1.32) from the contract geometry. Writes docs/rev-b-mating-report.md.

Skips cleanly if FreeCAD's Part module or the STEP files are unavailable.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
FAB = os.path.join(REPO, "fab", "minimal-vga", "revb")
C = json.load(open(os.path.join(HERE, "mating.json")))
CARDS = ("mem", "io", "cpu")          # seated cards (backplane is the host)
PCB_T = 1.6                            # nominal board thickness (mm)

try:
    import Part  # noqa: E402  (provided by FreeCAD)
except Exception as e:
    print(f"  SKIP  mate_check: FreeCAD Part unavailable ({e})")
    sys.exit(0)


def bbox(card):
    path = os.path.join(FAB, f"{card}.step")
    if not os.path.isfile(path):
        return None
    shp = Part.Shape()
    shp.read(path)
    bb = shp.BoundBox
    return {"x": bb.XLength, "y": bb.YLength, "z": bb.ZLength,
            "zmin": bb.ZMin, "zmax": bb.ZMax}


def main():
    boxes = {c: bbox(c) for c in CARDS}
    if any(v is None for v in boxes.values()):
        print("  SKIP  mate_check: some card STEP files missing (run the pipeline first)")
        return 0

    pitch = C["slot_pitch"]
    # Component envelope normal to the board = the STEP's Z extent. KiCad exports the
    # board around Z=0 with parts on top; ZLength is the full slab thickness. Cards seat
    # same-facing, so the worst adjacent pair needs (thickness_k) < pitch to clear.
    thickest = max(boxes.values(), key=lambda b: b["z"])
    thickest_card = max(boxes, key=lambda c: boxes[c]["z"])
    clearance = pitch - thickest["z"]

    # Keying (D1.4/D1.32): a correctly-oriented card presents its ext row at ext_row_x;
    # a card reversed 180 about the board centre (x=BOARD_W/2) mirrors it to
    # BOARD_W - ext_row_x. The base row is centred (x=base_row_x=BOARD_W/2) so it maps
    # onto itself under the flip and still seats — so keying can only come from the ext
    # row landing where there is no socket.
    board_w = 100.0
    ext_ok = C["ext_row_x"]
    ext_rev = board_w - C["ext_row_x"]
    base_symmetric = abs(C["base_row_x"] - board_w / 2.0) < 0.01

    lines = []
    lines.append("# VJUGA rev B — mechanical mating report (TG.3 / D1.15)\n")
    lines.append("Generated by `kicad/revb/mate_check.py` under FreeCAD from the four card "
                 "STEP models and `mating.json`. Distances in mm.\n")
    lines.append("## Card component envelopes (from STEP)\n")
    lines.append("| card | board X | board Y | envelope Z (thickness) |")
    lines.append("|---|---:|---:|---:|")
    for c in CARDS:
        b = boxes[c]
        lines.append(f"| {c} | {b['x']:.1f} | {b['y']:.1f} | {b['z']:.2f} |")
    lines.append("")
    lines.append("## Seated clearance (same-facing, contract slot pitch)\n")
    lines.append(f"- Slot pitch: **{pitch:.1f} mm**")
    lines.append(f"- Thickest card envelope: **{thickest['z']:.2f} mm** ({thickest_card})")
    lines.append(f"- Adjacent-card clearance = pitch − thickest = **{clearance:.2f} mm** "
                 f"→ {'PASS (no collision)' if clearance > 0 else 'FAIL (cards collide)'}")
    lines.append("")
    lines.append("> Conservative: the envelope Z includes the bus-connector pins, which "
                 "insert *into the backplane* rather than toward the neighbouring card, so "
                 "the true card-to-card gap is larger than the number above. Bench "
                 "measurement (T1.11) is the final check.")
    lines.append("")
    lines.append("## Reversed-card keying (D1.4 / D1.32)\n")
    lines.append(f"- Correct ext row X = {ext_ok:.2f}; reversed (flip about x={board_w/2:.0f}) "
                 f"→ X = {ext_rev:.2f} (no socket there).")
    lines.append(f"- Base row centred at x={C['base_row_x']:.1f} "
                 f"({'symmetric — maps onto its own socket under the flip' if base_symmetric else 'asymmetric'}).")
    lines.append("- **Finding:** because the base connector is centred and symmetric, a "
                 "reversed card's base pins still enter the base socket; keying can only "
                 "come from the ext row. With generic 0.1\" headers modelled here we cannot "
                 "prove the ext male pins bottom out on the bare backplane before the base "
                 "seats, so **mechanical keying is not guaranteed to self-enforce**.")
    lines.append("- **Decision (D1.32b):** adopt RC2014-precedent **convention-only** "
                 "orientation — silk pin-1 arrows on both card and backplane, and a "
                 "polarity notch mark — and record the residual mis-insertion risk. A "
                 "generator-emitted blocking post (D1.32a) remains available if bench "
                 "experience shows convention is insufficient; it needs a card clearance "
                 "hole at the mirrored-ext X and is deferred to avoid over-design.")
    lines.append("")
    report = os.path.join(REPO, "spinoffs", "minimal-vga", "docs", "rev-b-mating-report.md")
    open(report, "w").write("\n".join(lines) + "\n")

    print(f"mate_check: thickest {thickest_card} envelope {thickest['z']:.2f} mm, "
          f"pitch {pitch:.1f} mm -> clearance {clearance:.2f} mm "
          f"({'PASS' if clearance > 0 else 'FAIL'})")
    print(f"  reversed ext lands at x={ext_rev:.2f} (no socket); keying = convention-only (D1.32b)")
    print(f"  wrote {os.path.relpath(report, REPO)}")
    return 0 if clearance > 0 else 1


sys.exit(main())
