#!/usr/bin/env python3
"""R5.I7 assembled-card envelope and orientation report. Run under FreeCAD:

    freecadcmd mate_check.py

The STEP models prove the populated component envelopes normal to each PCB. The
exact Video VGA footprint/datasheet contract separately proves cable access;
the custom VGA footprint has no 3-D body, so its shell must not be inferred from
the STEP bounding box.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
FAB = os.path.join(REPO, "fab", "minimal-vga", "revb")
MATING = json.load(open(os.path.join(HERE, "mating.json"), encoding="utf-8"))
PHYSICAL = json.load(open(os.path.join(HERE, "five-board-physical.json"), encoding="utf-8"))
SLOTS = ((1, "cpu"), (2, "mem"), (3, "io"), (5, "video"))

try:
    import Part  # noqa: E402  (provided by FreeCAD)
except Exception as exc:
    print(f"  SKIP  mate_check: FreeCAD Part unavailable ({exc})")
    sys.exit(0)


def bbox(card):
    path = os.path.join(FAB, f"{card}.step")
    if not os.path.isfile(path):
        raise FileNotFoundError(path)
    shape = Part.Shape()
    shape.read(path)
    bb = shape.BoundBox
    return {"x": bb.XLength, "y": bb.YLength, "z": bb.ZLength,
            "zmin": bb.ZMin, "zmax": bb.ZMax}


def main():
    try:
        boxes = {card: bbox(card) for _, card in SLOTS}
    except FileNotFoundError as exc:
        print(f"  FAIL  mate_check: missing STEP model {exc.args[0]}")
        return 1

    stack = PHYSICAL["board_stack"]
    pitch = MATING["slot_pitch"]
    if abs(pitch - stack["slot_pitch_mm"]) > 1e-9:
        print("  FAIL  mate_check: physical and mating contracts disagree on slot pitch")
        return 1

    gaps = []
    for (left_slot, left), (right_slot, right) in zip(SLOTS, SLOTS[1:]):
        # Same-facing cards: the right card's underside starts at its ZMin and
        # the left card's component side ends at its ZMax.
        gap = (right_slot - left_slot) * pitch + boxes[right]["zmin"] - boxes[left]["zmax"]
        gaps.append((left, right, gap))
    minimum_gap = min(gap for _, _, gap in gaps)
    required_gap = stack["minimum_adjacent_clearance_mm"]

    # Reversed-card keying remains convention-only: the centred base row can
    # enter its socket even though the asymmetric extension row cannot.
    board_w = 100.0
    ext_ok = MATING["ext_row_x"]
    ext_rev = board_w - ext_ok
    base_symmetric = abs(MATING["base_row_x"] - board_w / 2.0) < 0.01
    vga_projection = stack["vga_shell_projection_mm"]

    lines = [
        "# VJUGA rev B — five-board mechanical mating report (R5.I7)",
        "",
        "Generated by `kicad/revb/mate_check.py` under FreeCAD from all four populated "
        "card STEP models, `mating.json`, and `five-board-physical.json`. Distances are mm.",
        "",
        "## Populated card envelopes from STEP",
        "",
        "| slot | card | envelope X | envelope Y | Z min | Z max | Z extent |",
        "|---:|---|---:|---:|---:|---:|---:|",
    ]
    for slot, card in SLOTS:
        box = boxes[card]
        lines.append(f"| {slot} | {card} | {box['x']:.2f} | {box['y']:.2f} | "
                     f"{box['zmin']:.3f} | {box['zmax']:.3f} | {box['z']:.3f} |")
    lines.extend([
        "",
        "The STEP Y envelope includes connector posts where their supplied 3-D models "
        "extend beyond a PCB edge. It does **not** model the custom VGA connector body.",
        "",
        "## Assembled same-facing clearance",
        "",
        f"Slot pitch is **{pitch:.1f} mm**. The first article uses CPU/Memory/I/O in "
        "slots 1/2/3, deliberately leaves slot 4 empty, and places Video in end slot 5.",
        "",
        "| adjacent occupied cards | computed surface gap | result |",
        "|---|---:|---|",
    ])
    for left, right, gap in gaps:
        lines.append(f"| {left} -> {right} | {gap:.2f} | "
                     f"{'PASS' if gap >= required_gap else 'FAIL'} |")
    lines.extend([
        "",
        f"Minimum assembled gap is **{minimum_gap:.2f} mm** against the frozen "
        f"**{required_gap:.2f} mm** minimum.",
        "",
        "## VGA cable access",
        "",
        f"Video is in the end slot, with slot 4 empty. The checked exact VGA footprint "
        f"places the connector mating face **{vga_projection:.2f} mm beyond the Video "
        "top PCB edge**, so a straight VGA plug exits away from the card stack. This is "
        "footprint/datasheet evidence (`rev-b-video-parts.md`), not a STEP-body claim.",
        "",
        "## Reversed-card keying",
        "",
        f"The correct extension row is at X={ext_ok:.2f}; a 180-degree reversed card "
        f"moves it to X={ext_rev:.2f}, where no socket exists. The base row is "
        f"{'centred and symmetric' if base_symmetric else 'not symmetric'}.",
        "",
        "Keying is therefore **convention-only**: matching pin-1/orientation silk is "
        "mandatory and insertion/removal must occur with power off. The extension row "
        "does not prove a hard mechanical block against partial reversed insertion.",
        "",
        "## Result",
        "",
        f"**{'PASS' if minimum_gap >= required_gap else 'FAIL'}** — all four populated "
        "card envelopes clear at the frozen slot assignment; end-slot VGA cable access "
        "and the residual convention-only orientation risk are explicitly recorded.",
        "",
    ])
    report = os.path.join(REPO, "spinoffs", "minimal-vga", "docs", "rev-b-mating-report.md")
    open(report, "w", encoding="utf-8").write("\n".join(lines))

    print(f"mate_check: minimum assembled gap {minimum_gap:.2f} mm "
          f"(required {required_gap:.2f} mm) -> "
          f"{'PASS' if minimum_gap >= required_gap else 'FAIL'}")
    print(f"  VGA mating face projects {vga_projection:.2f} mm by exact footprint contract")
    print(f"  wrote {os.path.relpath(report, REPO)}")
    return 0 if minimum_gap >= required_gap else 1


sys.exit(main())
