#!/usr/bin/env python3
"""TI.2 gate — resolve/enforce the crop-vs-letterbox decision (D2.4) against the oracle.

The 320x241 mono source pixel-doubles to 640x482, two lines over the 480 active raster,
so one doubled source row must go. video-timing.json freezes vertical_fit=crop_bottom
(drop the 241st source row, index 240). This checker confirms that choice is lossless for
the framebuffer the oracle actually produces: it reads cosim/vram.bin (regenerated by the
boot oracle upstream) and asserts every source row that crop would drop is blank.

Skips cleanly if cosim/vram.bin is absent. Exit 1 if a cropped row carries content
(meaning the frozen fit would lose pixels — flip video-timing.json to letterbox).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
VRAM = os.path.join(REPO, "cosim", "vram.bin")
T = json.load(open(os.path.join(HERE, "video-timing.json")))
fb = T["framebuffer"]
COLS, ROWS = fb["cols_bytes"], fb["rows"]
fit = T["scanout"]["vertical_fit"]

if not os.path.isfile(VRAM):
    print("  SKIP  video crop check: cosim/vram.bin not present (run the boot oracle first)")
    sys.exit(0)

data = open(VRAM, "rb").read()
if len(data) != COLS * ROWS:
    print(f"  SKIP  video crop check: vram.bin is {len(data)} bytes, expected {COLS*ROWS}")
    sys.exit(0)


def row_bits(r):
    return sum(bin(b).count("1") for b in data[r * COLS:(r + 1) * COLS])


# rows that the frozen fit drops from the visible raster
if fit == "crop_bottom":
    dropped = [ROWS - 1]                 # source row 240 only
elif fit == "letterbox":
    dropped = []                          # letterbox keeps all rows (clips half-lines)
else:
    print(f"video crop check: unknown vertical_fit '{fit}'")
    sys.exit(1)

used = sum(1 for r in range(ROWS) if row_bits(r) > 0)
bad = [(r, row_bits(r)) for r in dropped if row_bits(r) > 0]
if bad:
    print(f"video crop check FAILED (fit={fit}): dropped rows carry content: {bad}")
    print("    -> flip video-timing.json vertical_fit to 'letterbox'")
    sys.exit(1)
print(f"video crop check OK (fit={fit}): {used}/{ROWS} rows used, "
      f"dropped rows {dropped} blank -> lossless for this framebuffer")
