#!/usr/bin/env python3
"""Generate the deterministic C catalog embedded in JUKUWIN.EXE."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"generate-jukuwin-payloads: {message}")


def byte_rows(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        values = ", ".join(f"0x{value:02x}u" for value in data[offset:offset + 12])
        rows.append(f"    {values},")
    return "\n".join(rows)


def digest_initializer(digest: bytes) -> str:
    return ", ".join(f"0x{value:02x}u" for value in digest)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    manifest_bytes = args.manifest.read_bytes()
    manifest = json.loads(manifest_bytes)
    require(manifest.get("schema") == "jukuwin-embedded-payloads-v1",
            "unsupported manifest schema")
    payloads = manifest.get("payloads")
    require(isinstance(payloads, list) and len(payloads) == 4,
            "catalog must contain exactly four payloads")

    arrays = []
    entries = []
    seen = set()
    for item in payloads:
        symbol = item.get("symbol")
        require(isinstance(symbol, str) and
                re.fullmatch(r"[a-z][a-z0-9_]*", symbol) is not None,
                f"invalid symbol {symbol!r}")
        require(symbol not in seen, f"duplicate symbol {symbol}")
        seen.add(symbol)
        path = args.source_dir / item["file"]
        data = path.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        require(len(data) == item["bytes"],
                f"{path} size {len(data)} != {item['bytes']}")
        require(digest == item["sha256"],
                f"{path} SHA-256 {digest} != {item['sha256']}")
        arrays.append(
            f"static const uint8_t payload_{symbol}[] = {{\n"
            f"{byte_rows(data)}\n"
            f"}};"
        )
        entries.append(
            "    {\n"
            f"        \"{symbol}\", \"{item['mode']}\", \"{item['role']}\", "
            f"\"{item['format']}\",\n"
            f"        payload_{symbol}, sizeof(payload_{symbol}),\n"
            "        {\n"
            f"            \"{item['file']}\", UINT64_C({item['bytes']}),\n"
            f"            {{{digest_initializer(bytes.fromhex(digest))}}}\n"
            "        }\n"
            "    },"
        )

    revision = manifest["source"]["revision_full"]
    manifest_sha = hashlib.sha256(manifest_bytes).hexdigest()
    source = f"""/* Generated by tools/generate-jukuwin-payloads.py.
 * Manifest SHA-256: {manifest_sha}
 * Do not edit by hand.
 */
#include "jukuwin_payloads.h"

#include "jukuhost.h"

#include <stdio.h>
#include <string.h>

{chr(10).join(arrays)}

const struct jh_jukuwin_payload jh_jukuwin_payload_catalog[] = {{
{chr(10).join(entries)}
}};

const size_t jh_jukuwin_payload_catalog_count =
    sizeof(jh_jukuwin_payload_catalog) /
    sizeof(jh_jukuwin_payload_catalog[0]);

const char jh_jukuwin_payload_source_revision[] = "{revision}";

const struct jh_jukuwin_payload *jh_jukuwin_payload_find(
    const char *mode, const char *role)
{{
    size_t index;
    if (mode == NULL || role == NULL) return NULL;
    for (index = 0u; index < jh_jukuwin_payload_catalog_count; ++index) {{
        const struct jh_jukuwin_payload *payload =
            &jh_jukuwin_payload_catalog[index];
        if (strcmp(payload->mode, mode) == 0 &&
                strcmp(payload->role, role) == 0) return payload;
    }}
    return NULL;
}}

int jh_jukuwin_payloads_selftest(char *message, size_t capacity)
{{
    size_t index;
    if (message == NULL || capacity == 0u) return JH_ERR_ARGUMENT;
    for (index = 0u; index < jh_jukuwin_payload_catalog_count; ++index) {{
        uint8_t digest[JH_SHA256_SIZE];
        const struct jh_jukuwin_payload *payload =
            &jh_jukuwin_payload_catalog[index];
        jh_sha256(payload->bytes, payload->length, digest);
        if ((uint64_t)payload->length != payload->identity.size ||
                memcmp(digest, payload->identity.sha256,
                       sizeof(digest)) != 0) {{
            (void)snprintf(message, capacity, "%s identity mismatch",
                           payload->symbol);
            return JH_ERR_FORMAT;
        }}
    }}
    if (jh_jukuwin_payload_find("stock", "system") == NULL ||
            jh_jukuwin_payload_find("stock", "fastboot") == NULL ||
            jh_jukuwin_payload_find("c11", "system") == NULL ||
            jh_jukuwin_payload_find("c11", "fastboot") == NULL) {{
        (void)snprintf(message, capacity, "payload pair missing");
        return JH_ERR_FORMAT;
    }}
    (void)snprintf(message, capacity, "%lu payloads verified",
                   (unsigned long)jh_jukuwin_payload_catalog_count);
    return JH_OK;
}}

int jh_jukuwin_apply_payloads(const char *mode,
                              struct jh_host_options *options)
{{
    const struct jh_jukuwin_payload *system;
    const struct jh_jukuwin_payload *fastboot;
    if (mode == NULL || options == NULL) return JH_ERR_ARGUMENT;
    system = jh_jukuwin_payload_find(mode, "system");
    fastboot = jh_jukuwin_payload_find(mode, "fastboot");
    if (system == NULL || fastboot == NULL) return JH_ERR_UNSUPPORTED;
    options->system_bytes = system->bytes;
    options->system_length = system->length;
    options->system_identity = &system->identity;
    options->fast_stage_bytes = fastboot->bytes;
    options->fast_stage_length = fastboot->length;
    options->fast_stage_identity = &fastboot->identity;
    options->direct_fastboot = strcmp(mode, "c11") == 0;
    options->recover_session = options->direct_fastboot;
    return JH_OK;
}}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="ascii", newline="\n")
    print(
        "JUKUWIN-PAYLOAD-GENERATOR: PASS "
        f"({len(payloads)} payloads, manifest {manifest_sha})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
